# Generated by Django 5.2.4 on 2025-07-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
