# Generated by Django 5.2.4 on 2025-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_studentprofile_guardian_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='speciality',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
