# Generated by Django 5.2.4 on 2025-08-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_teacherprofile_cv_teacherprofile_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
