# Generated by Django 5.2.4 on 2025-08-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_studentprofile_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='document_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
