# Generated by Django 5.2.4 on 2025-08-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_document_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at'], 'permissions': [('add_superadmin', 'Puede crear super administradores'), ('add_admin', 'Puede crear administradores')], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
