# Generated by Django 5.2.4 on 2025-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('members', '0006_alter_member_document_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('name', 'classroom_manager'), name='unique_name'),
        ),
    ]
