# Generated by Django 5.2.4 on 2025-08-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_classroom_unique_name_and_more'),
        ('members', '0006_alter_member_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.teacherprofile'),
        ),
    ]
