# Generated by Django 5.2.4 on 2025-08-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_classroom_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='label',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
