# Generated by Django 5.2.4 on 2025-08-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_classroom_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='classroom',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
