# Generated by Django 5.2.4 on 2025-08-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_classroom_options_classroom_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'label')},
        ),
    ]
