# Generated by Django 5.2.4 on 2025-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
