# Generated by Django 5.2.4 on 2025-07-31 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_furnitureassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureassignment',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_furniture', to='inventory.furniture'),
        ),
        migrations.AlterField(
            model_name='furnitureassignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
