# Generated by Django 5.2.4 on 2025-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_furnitureassignment_furniture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=120, unique=True),
        ),
    ]
