# Generated by Django 5.2.4 on 2025-08-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_furniture_available_alter_furniture_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ('-created_at',), 'verbose_name': 'Furniture', 'verbose_name_plural': 'Furnitures'},
        ),
    ]
